title: Text und Tiefe
description: Essays, Gedanken und Kurzgeschichten über Wahrnehmung, Emotion und Menschsein
theme: just-the-docs
color_scheme: dark

url: "https://www.textundtiefe.de"
baseurl: ""

toc_label: "Inhalt"
search_enabled: false
nav_enabled: true
heading_anchors: false

just_the_docs:
  custom_css:
    - assets/css/custom.css

nav:
  - title: Home
    url: /

favicon_ico: /assets/images/favicon.ico

sass:
  style: compressed

