title: Text und Tiefe
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs
color_scheme: dark

url: "https://ichfragmich.github.io"
baseurl: "/TextundTiefe"



search_enabled: false

nav_enabled: true

heading_anchors: false


nav:
  - title: Home
    url: /


