title: Text und Tiefe
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs
color_scheme: dark

url: https://just-the-docs.github.io


search_enabled: false

nav_enabled: true

heading_anchors: false


nav:
  - title: Home
    url: /


